version: "3.7"
services:
  postgres:
    build: ./postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
  # kong-migrate:
  #   build: ./kong-migrate
  #   environment:
  #     - KONG_DATABASE=postgres
  #     - KONG_PG_HOST=postgres
  #     - KONG_PG_DATABASE=kong
  #     - KONG_PG_PASSWORD=kong
  #   depends_on:
  #     - postgres
  kong:
    build: ./kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"