version: "3.7"
services:
  postgres:
    build: ./postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
  kong-migrate:
    build: ./kong-migrate
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
    depends_on:
      - postgres
  kong:
    build: ./kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=127.0.0.1:8001
    depends_on:
      - postgres
      - kong-migrate
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"