version: "3.7"
services:
  postgres:
    build: ./postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
  kong-migrate:
    build: ./kong-migrate
    environment:
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_DATABASE=kong
    depends_on:
      - postgres
  kong:
    build: ./kong
    environment:
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_DATABASE=kong
    depends_on:
      - kong-migrate
      - postgres
    ports:
      - "8000:8000"