version: "3.7"
services:
  postgres:
    build: ./postgres
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
  kong:
    build: ./kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
  kong-gui:
    build: ./kong-gui
    depends_on:
      - postgres
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=postgres
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_DATABASE=kong
    ports:
      - "1337:1337"